# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      db-count: 2
      tb-count: 4
      db-default: db00
      router-key: uId
      db-list: db01, db02
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/Lottery?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/Lottery?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password:
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/Lottery?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: